/*
 * This file was automatically generated by EvoSuite
 * Mon May 25 19:41:06 GMT 2020
 */

package name.abuchen.portfolio.snapshot.security;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import name.abuchen.portfolio.model.AccountTransaction;
import name.abuchen.portfolio.model.PortfolioTransaction;
import name.abuchen.portfolio.model.Security;
import name.abuchen.portfolio.money.CurrencyConverter;
import name.abuchen.portfolio.money.Money;
import name.abuchen.portfolio.snapshot.security.DeltaCalculation;
import name.abuchen.portfolio.snapshot.security.DividendFinalTransaction;
import name.abuchen.portfolio.snapshot.security.DividendInitialTransaction;
import name.abuchen.portfolio.snapshot.security.DividendTransaction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeltaCalculation_ESTest extends DeltaCalculation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      deltaCalculation0.setTermCurrency("");
      Money money0 = deltaCalculation0.getDelta();
      assertFalse(money0.isPositive());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      // Undeclared exception!
      try { 
        deltaCalculation0.getDeltaPercent();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.DELIVERY_OUTBOUND;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, "null", 1060L, security0, 1060L, portfolioTransaction_Type0, 1060L, 1060L);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.DELIVERY_INBOUND;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, ")gUb-U9HN,", 1060L, security0, 151L, portfolioTransaction_Type0, 1060L, 151L);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.TRANSFER_OUT;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, ")gUb-U9HN,", 1060L, security0, 1060L, portfolioTransaction_Type0, 1060L, 1060L);
      deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
      assertNull(portfolioTransaction0.getNote());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.SELL;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, "kkjYKJ/U>H,", 1050L, security0, (-133L), portfolioTransaction_Type0, (-133L), 0L);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.TRANSFER_IN;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, "u@]`F@> >r", 1060L, security0, (-1L), portfolioTransaction_Type0, (-1L), 1060L);
      deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
      assertNull(deltaCalculation0.getTermCurrency());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Security security0 = new Security();
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      PortfolioTransaction.Type portfolioTransaction_Type0 = PortfolioTransaction.Type.BUY;
      PortfolioTransaction portfolioTransaction0 = new PortfolioTransaction((LocalDateTime) null, "kkjYKJ/U>H,", 1060L, security0, 1060L, portfolioTransaction_Type0, 1060L, 0L);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, portfolioTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      LocalDateTime localDateTime0 = MockLocalDateTime.of(8, 8, 8, 8, 8, 8);
      Security security0 = new Security("", "");
      AccountTransaction.Type accountTransaction_Type0 = AccountTransaction.Type.INTEREST;
      AccountTransaction accountTransaction0 = new AccountTransaction(localDateTime0, "", 8, security0, accountTransaction_Type0);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, accountTransaction0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      Security security0 = new Security();
      AccountTransaction.Type accountTransaction_Type0 = AccountTransaction.Type.FEES_REFUND;
      AccountTransaction accountTransaction0 = new AccountTransaction(localDateTime0, "", 1060L, security0, accountTransaction_Type0);
      AccountTransaction.Type accountTransaction_Type1 = AccountTransaction.Type.TAX_REFUND;
      accountTransaction0.setType(accountTransaction_Type1);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, accountTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      Security security0 = new Security();
      AccountTransaction.Type accountTransaction_Type0 = AccountTransaction.Type.TAXES;
      AccountTransaction accountTransaction0 = new AccountTransaction(localDateTime0, "", 1060L, security0, accountTransaction_Type0);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, accountTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      Security security0 = new Security();
      AccountTransaction.Type accountTransaction_Type0 = AccountTransaction.Type.FEES_REFUND;
      AccountTransaction accountTransaction0 = new AccountTransaction(localDateTime0, "", 1060L, security0, accountTransaction_Type0);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, accountTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      Security security0 = new Security();
      AccountTransaction.Type accountTransaction_Type0 = AccountTransaction.Type.FEES;
      AccountTransaction accountTransaction0 = new AccountTransaction(localDateTime0, "", 1060L, security0, accountTransaction_Type0);
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, accountTransaction0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, (DividendFinalTransaction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, (DividendInitialTransaction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      // Undeclared exception!
      try { 
        deltaCalculation0.visit((CurrencyConverter) null, (DividendTransaction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      deltaCalculation0.setTermCurrency("name.abuchen.portfolio.model.Transaction$ByDate");
      double double0 = deltaCalculation0.getDeltaPercent();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DeltaCalculation deltaCalculation0 = new DeltaCalculation();
      // Undeclared exception!
      try { 
        deltaCalculation0.getDelta();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("name.abuchen.portfolio.snapshot.security.DeltaCalculation", e);
      }
  }
}
